---
title: 'Assignment : Course Project 1'
author: "Manjula T"
date: "January 10, 2016"
output: md_document
---

### 1. Code for reading in the dataset and/or processing the data

```{r, echo=TRUE}
if(!file.exists("data"))  {
	dir.create("data")
}

if(!file.exists("./data/repdatadataactivity.zip"))  {
	zipFileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip?accessType=DOWNLOAD"
	download.file(zipFileUrl, destfile="./data/repdatadataactivity.zip")
}

if(!file.exists("./data/activity.csv")) {
	## check and correct the code to unzip
	unzip("./data/repdatadataactivity.zip", list=FALSE, overwrite=TRUE, exdir=".")
}

activitydata <- read.csv("./data/activity.csv")

```


### 2.Histogram of the total number of steps taken each day
```{r, echo=TRUE}
## Load plyr Package
	library(plyr)

## Group by the date and then sum the steps
  act_sum_by_date <- ddply(activitydata, "date", summarise, TotalSteps=sum(steps))

## Plot the histogram 
	hist(act_sum_by_date$TotalSteps, 
				xlab="Total Number of Steps",
				main="Histogram of Total Number of Steps taken each Day")

```

### 3.Mean and median number of steps taken each day
### MEAN
```{r, echo=TRUE}
## Load plyr Package
	library(plyr)

## Group by the date and then find mean of the steps
  act_mean_by_date <- ddply(activitydata, "date", summarise, MeanSteps=mean(steps))
	
## Print the means
  print(act_mean_by_date)

## Plot the Graph (Base Plotting System)
	plot(act_mean_by_date$date, act_mean_by_date$MeanSteps, 
				type="l", xlab="Date", ylab="Mean of Steps",
				main="Mean of Steps taken each Day")

```

### MEDIAN
```{r, echo=TRUE}
## Load plyr Package
	library(plyr)

## Group by the date and then find the median of the steps
  act_median_by_date <- ddply(activitydata, "date", summarise, MedianSteps=median(steps))
  
## Print the medians
  print(act_median_by_date)

## Plot the Graph (Base Plotting System)
	plot(act_median_by_date$date, act_median_by_date$MedianSteps, 
				type="l", xlab="Date", ylab="Median of Steps",
				main="Median of Steps taken each Day")

```

### 4. Time series plot of the average number of steps taken
```{r, echo=TRUE}
## Load plyr Package
	library(plyr)
	library(ggplot2)

## Group by the date and then find the median of the steps
  act_avg_by_interval <- ddply(activitydata, "interval", summarise, mean(steps,na.rm=TRUE))
  colnames(act_avg_by_interval )[2] <- "AverageSteps"
  
## Finding the range for interval
	int_range <- range(0,  act_avg_by_interval$interval)

## Plot the Graph (Base Plotting System)
	ThePlot <- qplot(interval, AverageSteps, data=act_avg_by_interval,
	      geom="line", method="lm",xlab="Interval", ylab="Average of Steps", 
				main="Average of Steps taken per interval", xlim=int_range)
	
	## Printing the Plot
	print(ThePlot)
	
```

### 5. The 5-minute interval that, on average, contains the maximum number of steps
```{r, echo=TRUE}
act_order <- act_avg_by_interval[order(act_avg_by_interval[,2]),]

act_max <- tail(act_order,1)
colnames(act_max )[1] <- "Interval"
colnames(act_max )[2] <- "Highest Average Step"	

print(act_max)
```